version: "3"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=wordgame.zooted.app,wordgame.localhost
      - LETSENCRYPT_HOST=wordgame.zooted.app,wordgame.localhost
  backend:
    build: ./server
    restart: always
    ports:
      - "2567:2567"
    environment:
      - VIRTUAL_HOST=api.zooted.app,api.localhost
      - LETSENCRYPT_HOST=api.zooted.app,api.localhost
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    depends_on:
      - backend
      - frontend
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=mattjdelsig@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
