version: "3"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=wordgame.zooted.app,wordgame.localhost
  backend:
    build: ./server
    restart: always
    ports:
      - "2567:2567"
    environment:
      - VIRTUAL_HOST=api.zooted.app,api.localhost
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend
      - frontend
