version: "3"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: ./server
    restart: always
    ports:
      - "2567:2567"
